<a href="https://colab.research.google.com/github/Kranthi9269/aiml-lab/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#implement basic data structures using numpy,pandas





In [ ]:
#list

In [ ]:
list=['apple','year','bat','cat']
print(list)
print(type(list))

['apple', 'year', 'bat', 'cat']
<class 'list'>


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])


print(arr)


print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# New Section

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],[ 1,2,3]])
arr1 = np.array([[4, 5, 6],[6, 7, 8]])

m=np.multiply(arr,arr1)
print(m)
n=np.divide(arr,arr1)
print(n)
print(arr+arr1)
k=np.power(arr,arr1)
print(k)



[[ 4 10 18]
 [ 6 14 24]]
[[0.25       0.4        0.5       ]
 [0.16666667 0.28571429 0.375     ]]
[[ 5  7  9]
 [ 7  9 11]]
[[   1   32  729]
 [   1  128 6561]]


In [ ]:
print(np.sin(np.pi/2))

1.0


In [ ]:
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
print(np.exp([2,3]))

[ 7.3890561  20.08553692]


In [ ]:
ar1=["sr"]
ar2=["universiity"]
print(np.concatenate((ar1, ar2), axis=0))

['sr' 'universiity']
