In [3]:

##operations on arrays
import numpy as np

arr = np.array([[1, 2, 3],[ 1,2,3]])
arr1 = np.array([[4, 5, 6],[6, 7, 8]])

m=np.multiply(arr,arr1)
print(m)
n=np.divide(arr,arr1)
print(n)
print(arr+arr1)
k=np.power(arr,arr1)
print(k)

[[ 4 10 18]
 [ 6 14 24]]
[[0.25       0.4        0.5       ]
 [0.16666667 0.28571429 0.375     ]]
[[ 5  7  9]
 [ 7  9 11]]
[[   1   32  729]
 [   1  128 6561]]
